name: 'Setup mint'
description: 'Set up mint swift package manager'
author: 'irgaly'
inputs:
  bootstrap:
    description: 'execute mint bootstrap'
    required: false
    default: 'true'
  use-cache:
    description: 'Cache installed swift tools'
    required: false
    default: 'true'
  cache-prefix :
    description: 'Cache key prefix'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
