name: Test

on:
  push:
    branches:
      - main

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: irgaly/setup-mint@main
        with:
          mint-directory: example
      - shell: bash -xe {0}
        run: |
          ls -alh "$HOME/bin" | grep mint
          "$HOME/bin/mint" --version
          "$HOME/bin/mint" list
          ls -alh ~/.mint
          ls -alh ~/.mint/packages/*/build/*
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: irgaly/setup-mint@main
        with:
          mint-directory: example
      - shell: bash -xe {0}
        run: |
          ls -alh "$HOME/bin" | grep mint
          "$HOME/bin/mint" --version
          "$HOME/bin/mint" list
          ls -alh ~/.mint
          ls -alh ~/.mint/packages/*/build/*
